activate=активировать
deactivate=деактивировать
kill=убить
kills=убийства
game_starting=игра начинается
game_ending=игра заканчивается
the_game=игра
game=игра
weapon=оружие
gun=оружие
water=вода
select_weapon=выберите оружие
select_vehicle=выберите транспорт
select_class=выберите класс
select_character=выберите персонажа
select_model=выберите модель
select=выбрать
vehicle=транспорт
class=класс
character=персонаж
model=модель
money=деньги
currency=валюта
stamina=выносливость
intelligence=интеллект
craftiness=хитрость
strength=сила
dexterity=ловкость
phone_keys=клавиши телефона
health=здоровье
walk=ходить
run=бежать
walking=ходьба
running=бег
drink=пить
eat=есть
drinking=питьё
eating=поедание
shooting=стрельба
shot=выстрелить
driving=вождение
smoke=курить
smoking=курение
grenade=граната
died=умер
dead=мёртвый
is_dead=мёртв
plant=растение
tool=инструмент
street=улица
traitor=предатель
police=полиция
police_unit=полицейское подразделение
road=дорога
flying=полёт
house=дом
hospital=госпиталь
tree=дерево
mountain=гора
grass=трава
hills=холмы
rock=камень
traffic_light=светофор
knife=нож
male=мужчина
female=женщина
turn_on=включить
turn_off=выключить
job=работа
hitting=попадание
falling=падение
message_of_the_day=сообщение дня
i_accept=Я принимаю
i_decline=Я отклоняю
help=помощь
broadcast=трансляция
radio=радио
frequency=частота
shop=магазин
building=строение
fire=огонь
wood=древесина
drunk=пьяный
fire_fighter=пожарник
police_officer=офицер полиции
paramedic=фельдшер
mayor=мэр
bus_driver=водитель автобуса
president=президент
criminal=преступник
vote=голос
helicopter=вертолёт
mouse_pad=Коврик для мыши
raid=налёт
weapons=оружия
door=дверь
apartment=квартира
danger=опасность
attention=внимание
dangerous=опасный
keyboard=клавиатура
lake=озеро
food=еда
friendly_fire=огонь по своим
lighter=зажигалка
twilight=сумерки
laws=законы
permanent=постоянный
ban_permanently=заблокировать навсегда
permanently_banned=заблокирован навсегда
kick=выгнать
screenshot=скриншот
reason=причина
arrest=арестовать
warrant=ордер
warrant_arrest=ордер на арест
unarrest=освободить
cuffs=наручники
stick=дубинка
warrant_search=ордер на обыск
unconscious=без сознания
fine=штраф
kicked_for=выгнан за
banned_for=заблокирован за
screensaver=заставка
defence=защита
garden=сад
mobile=мобильный
menu=меню
hotdog=хот-дог
calculator=калькулятор
sms_mobile=СМС
open=открыть
close=закрыть
music=музыка
lock=запереть
unlock=отпереть
advertising=реклама
listening_to_music=слушает музыку
dancing_with=танцует с
forum=форум
website=сайт
drug_dealer=наркоторговец
table=стол
chair=стул
waterfall=водопад
fountain=фонтан
feet=ноги
window=окно
head=голова
body=тело
rooftop=крыша
source=источник
burned=сгоревший
prop=объект
props=объекты
crash=крушение
burning=горение
explosion=взрыв
car_accident=автомобильная авария
cash=наличные
gunfire=выстрел
died_in=погиб в
died_in_a=погиб в
died_in_a_car_accident=погиб в автокатастрофе
sidewalk=тротуар
traffic_pole=дорожный столб
zebralines=пешеходный переход
roleplay=ролевая игра
random_deathmatch=случайный бой насмерть
car_deathmatch=автомобильный бой насмерть
hunted=преследуемый
awp=AWP
government=правительство
black_market_dealer=дилер чёрного рынка
car_jacked=угнана машина
handcuffs=наручники
brutal=жестокий
made_of=сделан из
being_with=находится с
shopping_cart=корзина
big_city=большой город
footpath=тропинка
kidnap=похитить
rope=верёвка
emergency=чрезвычайное положение
tunnel=туннель
bridge=мост
on_top_of=на вершине
zombie=зомби
crouch=присесть
emergency_call=экстренный вызов
device=устройство
jump=прыжок
makarov=Макаров
molotov=Молотов
chase=преследовать
priority_high=высокий
priority_medium=средний
roadblock=дорожное заграждение
spikes=шипы
spiked=убит шипами
freeze=заморозить
free=освободить
taze=ударить током
tazed=поражен электрошоком
afk_kick=выгнан за бездействие
bored=скучающий
afk=бездействие
away_from_keyboard=отошёл от клавиатуры
tax=налог
max_speed=максимальная скорость
speedlimit=ограничение скорости
checkpoint=контрольная точка
driving_license=водительские права
valid_driving_license=действительное водительское удостоверение
invalid_driving_license=недействительное водительское удостоверение
speedmeter=спидометр
be_right_back=скоро буду
fire_spread=распространение огня
license_checkpoint=контрольно-пропускной пункт
license=лицензия
gun_license=лицензия на оружие
illegal=незаконный
legal=законный
accident=происшествие
car_seat=автомобильное сиденье
alive=жив
still_alive=всё ещё жив
not_dead_yet=пока не мёртв
flower=цветок
cake=торт
died_at=умер в
needs_help_at=нуждается в помощи в
police_radio=полицейское радио
chat_yell=кричать
chat_whisper=шептать
chat_cry=плакать
talk=говорить
department=отделение
speeding=ускорение
arrested=арестован
cuffed=в наручниках
atm=банкомат
bank=банк
backup=подкрепление
car_alarm=автомобильная сигнализация
positive=положительный
negative=отрицательный
door_alarm=дверная сигнализация
door_lockpicking=взлом двери
ambulance=скорая помощь
car_fuel=автомобильное топливо
fire_truck=пожарная машина
map=карта
npc=НИП
cloths=ткани
driving_school=автошкола
driving_instructor=инструктор по вождению
driving_instructor_manager=менеджер инструктора по вождению
rare_props=редкие объекты
rare_prop=редкий объект
rare_item=редкий предмет
rare_items=редкие предметы
rare=редкий
admin=админ
donut=пончик
super_admin=суперадмин
owner=владелец
breach=прорыв
lockpick=отмычка
car_bomb=автомобильная бомба
garage_lady=гаражная дама
event=событие
race=гонка
boring_room_event=скучное комнатное событие
mini_game_event=мини-игровое событие
prices=цены
win=победа
fail=провал
loose=свободный
profit=выгода
hungry=голоден
starving=голодает
bullet=пуля
starvation=голодание
not_hungry=не голоден
metagaming=metagaming
ammo_box=коробка с боеприпасами
very_hungry=очень голоден
swep=скриптовое оружие
lua=lua
puke=тошнить
lost=проиграл
won=победил
is_winning=побеждает
is_losing=проигрывает
team_lost=команда проиграла
team_won=команда победила
winning_team=победившая команда
losing_team=проигравшая команда
suicide=самоубийство
commit_suicide=совершить самоубийство
fall_damage=урон от падения
damage=урон
roof_climbing=лазанье по крышам
fun_rating=рейтинг веселья
height=высота
length=длина
button=кнопка
scoreboard=таблица счёта
hotel=отель
hotel_room=номер в отеле
score=счёт
hide=скрыть
show=показать
seek=искать
game_points=игровые очки
present=подарок
entry=вход
exit=выход
cinema=кино
theater=театр
movie=фильм
computer_beamer=проектор
beach=пляж
computer=компьютер
monitor=монитор
computer_mouse=компьютерная мышь
computer_boxes=компьютерные коробки
computer_headset=гарнитура
floor=пол
rob=грабить
code=код
wallet=кошелёк
pocket=карман
credit_card=кредитная карта
credit_card_insert=вставьте кредитную карту
pin_code=пин-код
status=статус
friendly=дружелюбный
unfriendly=недружелюбный
enemy=враг
friend=друг
target=цель
north=север
south=юг
west=запад
east=восток
direction=направление
middle=середина
zoom_in=приблизить
zoom_out=отдалить
target_found=цель найдена
target_locked=цель захвачена
target_lost=цель потеряна
baby_doll=детская кукла
ragdoll=рэгдолл
chat_ooc=внеигровой чат
chat_looc=локальный внеигровой чат
chat_local=локальный чат
payment_method=способ оплаты
true=правда
false=ложь
do_you_really_want_to_do_that=вы действительно хотите сделать это
bullshit=чушь
success=успех
failure=неудача
caterpillars=гусеницы
oven=печь
fireplace=камин
error=ошибка
notice=уведомление
warning=предупреждение
lua_error=ошибка lua
console=чит
ban_request=запрос на блокировку
ban_appeal=апелляция блокировки
system_error=системная ошибка
internal_error=внутренняя ошибка
vip=vip
furniture=мебель
ip=ip
ddos=ddos
lag=лаг
lagging=лагает
administrator_applications=заявки на администрирование
proof=доказательство
right=право
left=лево
forward=вперёд
backward=назад
party=вечеринка
birthday=день рождения
birthday_party=вечеринка в честь дня рождения
server_maintenance=техническое обслуживание сервера
update=обновление
admin_abuse=злоупотребление статусом администратора
host=хост
admin_noclip=полёт
admin_stick=дубинка администратора
admin_swep=оружие администратора
admin_commands=команды администратора
propclimb=лазанье по объектам
logs=журналы
rule=правило
fair=справедливо
unfair=несправедливо
planting_shrooms=посадка грибов
server=сервер
hacker=хакер
cheats=читы
team_balance=баланс команд
auto_team_balance=автобаланс команд
you_were_moved_to_balance_teams=вас переместили для баланса команд
gravity=гравитация
gravitygun=грави-пушка
fists=кулаки
machine_guns=пулемёты
sub_machine_guns=пистолеты-пулемёты
heavy_machine_guns=тяжелые пулемёты
sniper=снайпер
pistols=пистолеты
keys=ключи
camera=камера
physgun=физпушка
m4a1=m4a1
ak47=ak47
fiveseven=fiveseven
mp5=mp5
glock=глок
shotgun=дробовик
uzi=узи
laserbeam=лазерный луч
chat=чат
organisation=организация
organisation_chat=чат организации
guide=руководство
discussion=обсуждение
bulletproof_vest=бронежилет
recoil=отдача
demote=понизить
promote=повысить
invite=пригласить
invite_accept=принять приглашение
invite_decline=отклонить приглашение
emote=эмоция
shoutbox=чат
profile=профиль
picture=изображение
sign=знак
bush=куст
traffic_sign=дорожный знак
traffic_cone=дорожный конус
blinking_traffic_cone=мигающий дорожный конус
dust=пыль
trash=мусор
trashcan=мусорный бак
dark_tunnel=тёмный туннель
skinny_fence=тонкий забор
fence=забор
connect_to=подключиться к
enemy_down=враг убит
report_in_team=доложить команде
bannable=наказуемо
npc_killed=НИП убит
map_restart=перезапуск карты
take_cover=сесть в укрытие
rush_in=ворваться
move_out=выдвинуться
stay_back=стоять позади
move_back=отойти назад
move_in=войти
slowly=медленно
fast=быстро
finished_off=добил
stalker=сталкер
accept=принять
decline=отклонить
trade=торговля
bug=ошибка
bugs=ошибки
stuck=застрять
elevator=лифт
office=офис
break_glass=разбитие стекла
break_window=разбитие окна
press=нажать
skybox=skybox
skin_color=цвет кожи
color=цвет
wall_color=цвет стены
ceiling=потолок
message=сообщение
door_closed=закрытая дверь
door_opened=открытая дверь
close_door=закрыть дверь
open_door=открыть дверь
burgler=взломщик
robber=грабитель
robbery=ограбление
suburban_area=пригородный район
car_dealer=продавец автомобилей
clothes_shop=магазин одежды
government_building=здание правительства
industrial_area=промышленная зона
warehouse=склад
jail=тюрьма
garage=гараж
shops=магазины
city=город
prison=тюрьма
emergency_station=травмпункт
behind=позади
materials=материалы
craft=создать
models=модели
entities=энтити
entity=энтити
mixture_table=таблица смесей
skills_table=таблица навыков
vehicle_acceleration=ускорение транспорта
vehicle_break=транспортный тормоз
vehicle_horn=транспортный гудок
vehicle_siren=сирены
script=скрипт
sound_effect=звуковой эффект
surface=поверхность
client=клиент
madness=безумие
rage=ярость
rage_quit=яростный выход
sickness=болезнь
street_signs=уличные знаки
citizen_radio=гражданское радио
street_lamps=уличные фонари
livestream=прямая трансляция
report=пожаловаться
garage_door=дверь гаража
players=игроки
player=игрок
park=парк
bench=скамейка
kissing=целует
spawn=точка возрождения
spawn_killing=убийство на точке возрождения
beer=пиво
action=действие
mayor_vote=выборы мэра
mayor_assassination=убийство мэра
spawnlist=список создаваемого
parking_spot=парковка
face=лицо
eye=глаз
nose=нос
mouth=рот
ear=ухо
information=информация
rule_break=нарушение правил
shop_closed=магазин закрыт
shop_opened=магазин открылся
shop_open=магазин открыт
close_shop=закрыть магазин
open_shop=открыть магазин
rules=правила
receive=получить
stove=печь
glassdoor=стеклянная дверь
electricity=электричество
no_electricity=нет электричества
bullet_hole=пулевое отверстие
fish=рыба
mailbox=почтовый ящик
roadtrip=поездка
member=участник
recruit=новобранец
event_host=организатор события
blood=кровь
suit=костюм
dead_body=труп
connect=подключиться
disconnect=отключиться
section=секция
speed=скорость
speed_limit=ограничение скорости
paint_job=красильная работа
general=общий
gang=банда
subway=метро
hallway=коридор
train_station=железнодорожный вокзал
train=поезд
content_pack=пакет содержимого
private=частный
new_player=новый игрок
person=человек
bus_route=автобусный маршрут
situation=ситуация
rank=ранг
citizen=гражданин
feature=особенность
propety=собственность
owned=приобретено
unowned=не приобретено
problem=проблема
bought=купил
sell=продать
buy=купить
weather=погода
day=день
night=ночь
sun=солнце
lightning=освещение
tornado=торнадо
development=разработка
server_rules=правила сервера
support=поддержка
donate=пожертвовать
issues=проблемы
armor=броня
energy=энергия
unlimited=неограниченный
texture=текстура
texture_bug=ошибка текстуры
blacklist=чёрный список
bus_stop=автобусная остановка
full=полный
empty=пустой
slot=слот
service=сервис
glitch=глюк
cliff=утёс
advert=рекламировать
number=число
advertisement=реклама
church=церковь
court=суд
lawyer=адвокат
stockmarket=фондовая биржа
dark=тёмный
light=свет
lamp=лампа
container=контейнер
wreckage=обломки
barrel=бочка
storage=склад
closet=шкаф
telephone=телефон
emergency_entrance=аварийный вход
sink=раковина
fridge=холодильник
cash_register=кассовый аппарат
sand=песок
dirt=грязь
toilet=туалет
television=телевидение
bed=кровать
painting=картина
shower=душ
couch=диван
bottle=бутылка
aquarium=аквариум
picnic_table=стол для пикника
chimney=дымоход
nitro=нитро
create_organisation=создать организацию
coffee=кофе
gender=пол
trust=доверие
jacket=куртка
beard=борода
generic=общий
billboard=рекламный щит
title=заголовок
resource=ресурс
particle=частица
media=медиа
hat=шапка
shadow=тень
shades=оттенки
system=система
data=данные
time=время
impact=удар
human=человек
item=предмет
casino=казино
debug=отладка
flame=пламя
rain=дождь
serious=серьёзный
newspaper=газета
time_player=отыгранное время
riotshield=полицейский щит
interior=интерьер
wheel=колесо
tire=шина
misc=разное
badge=значок
engine=двигатель
clock=часы
casing=корпус
onlinetime=время в сети
playtime=время в игре
session_time=время сессии
session_playtime=сессионное время в игре
total_playtime=общее время в игре
snow=снег
sold=продано
cloud=облако
enable=включить
disable=выключить
leaves=листья
drop=выкинуть
inventory=инвентарь
intro=вступление
loading=загрузка
loading_screen=загрузочный экран
crosshair=прицел
smile=улыбка
extra=дополнительный
scope=прицел
child=ребёнок
tie=связать
medkit=аптечка
crowbar=монтировка
fps=кадров в секунду
ping=пинг
garbage=мусор
dodge=увернуться
miss=промах
wire=провод
gascan=канистра с бензином
style=стиль
config=настройки
rear_light=задняя фара
front_light=передняя фара
trace=след
plate=тарелка
decal=декаль
shell=гильза
diffuse=распространить
base=база
stripes=полосы
chrome=хром
index=индекс
edit=редактировать
editor=редактор
undo=отменить
mirror=зеркало
scene=сцена
demo=повтор
render=прорисовать
user=пользователь
engineer=инженер
grip=захват
lens=линза
transmission=передача
gloves=перчатки
shader=шейдер
industrial=промышленный
cabin=хижина
shooting_range=стрельбище
metro=метро
trailer=трейлер
swimming_pool=бассейн
radio_station=радиостанция
club=клуб
chip=чип
background=фон
bottom=низ
decoration=декорация
contraband=контрабанда
liquid=жидкость
group=группа
alone=один
corpse=труп
eathquake=землетрясение
revive=возродить
register=зарегистрировать
breath=дыхание
maximum=максимум
minimum=минимум
doorbell=дверной звонок
digital=цифровой
ringtone=рингтон
infinite=бесконечный
throttle=дроссель
cruise=круиз
category=категория
categories=категории
idle=бездействие
fade=исчезать
outfit=костюм
platform=платформа
shared=общий
tutorial=руководство
global=глобальный
construct=строить
description=описание
project=проект
highlight=выделить
image=изображение
properties=свойства
physics=физика
turret=турель
blur=размытие
version=версия
input=ввод
output=вывод
spawnmenu=меню создания
tissue=ткань
flashlight=фонарик
skyscraper=небоскрёб
dynamic=динамичный
restart=перезапуск
blizzard=метель
untitled=без названия
stats=статистика
changelog=список изменений
equipment=снаряжение
gaspump=бензоколонка
lobby=лобби
security=безопасность
bathtub=ванна
panel=панель
piano=фортепиано
modern=современный
classic=классический
pipe=труба
unknown=неизвестный
complete=завершённый
incomplete=незавершённый
assault=нападение
default=по умолчанию
ignite=поджечь
achievement=достижение
universal=универсальный
reverse=обратить
start=начать
stop=остановить
round=раунд
custom=пользовательский
electronics=электроника
file=файл
copy=скопировать
paste=вставить
modification=модификация
configuration=конфигурация
remove_entity=удалить энтити
add_entity=добавить энтити
modify_entity=добавить энтити
morning=утро
evening=вечер
station=станция
rail=рельс
seats=сиденья
popcorn=попкорн
recording=запись
start_recording=начать запись
stop_recording=остановить запись
microphone=микрофон
use_item=использовать предмет
cable=кабель
switch=переключатель
lever=рычаг
insulated=изолированный
chocolate=шоколад
snack=закуска
spectating=наблюдение
start_spectating=начать наблюдение
stop_spectating=прекратить наблюдение
spawn_prop=создать объект
spawn_entity=создать энтити
remove_prop=удалить объект
kevlar_vest=кевларовый бронежилет
use_kevlar_vest=использовать кевларовый бронежилет
throw=бросить
pick_up=подобрать
throw_knife=бросить нож
pick_up_knife=подобрать нож
fishing=рыбалка
drowning=утопление
install=установить
today=сегодня
yesterday=вчера
tomorrow=завтра
preference=предпочтение
tag=метка
news=новости
canal=канал
professional=профессионал
ready=готов
award=награда
reward=награда
leaderboard=таблица лидеров
platoon=взвод
options=опции
set_options=установить опции
save_options=сохранить опции
active=активный
inactive=неактивный
sign_in=войти
sign_out=выйти
microwave=микроволновка
delete=удалить
battle=битва
tip=совет
hint=подсказка
zone=зона
inside=внутри
outside=снаружи
ticket=билет
refresh=обновить
filter=фильтр
only=только
set_time=установить время
region=регион
expansion=расширение
hands_up=руки вверх
other=другое
size=размер
preset=предустановка
show_all=показать всё
history=история
accessory=аксессуар
competition=соревнование
like=нравится
dislike=не нравится
brain=мозг
continue=продолжить
patch=обновление
story=история
pull=тянуть
trigger=триггер
left_mouse_click=нажатие левой кнопки мыши
right_mouse_click=нажатие правой кнопки мыши
middle_mouse_click=нажатие средней кнопки мыши
suppressor=подавитель
timed_out=время истекло
universe=вселенная
moon=луна
attachment=вложение
ship=корабль
common=общий
missile=ракета
release=выпустить
coordinate=координировать
invisible=невидимый
visible=видимый
need=нужда
complain=жаловаться
multiple=несколько
single=одиночный
final=окончательный
perfect=идеальный
unbalanced=несбалансированный
balanced=сбалансированный
destroy=уничтожить
realize=понять
opinion=мнение
decrease=уменьшить
increase=увеличить
accuracy=точность
fix=исправить
threat=угроза
agree=согласен
disagree=не согласен
alpha=альфа
beta=бета
awesome=потрясающий
recent=недавний
plugin=плагин
combat=борьба
technology=технология
cancel=отмена
direct=прямой
search.results=Результатов
search.result=Результат
search.none=Нет результатов
sort.random=Случайное
sort.newest=Новейшее
sort.oldest=Старейшее
category.featured=Рекомендуемое
dialog.ok=ОК
dialog.cancel=Отмена

#Singular of main_menu's "saves=Saves". Not the concept of saving, but the concept of a singluar Save.
saves.singular=Сохранение

fav.addto=Добавить в избранное
fav.removefrom=Удалить из избранного
dice.roll=Бросок
dice.reroll=Переброс
paginate.previous=Предыдущая
paginate.next=Следующая
paginate.first=Первая
paginate.last=Последняя
browser.back=Назад
browser.forward=Вперёд
network.reconnect=Перезайти
network.offline=Не в сети
network.online=В сети

chat.dead=*МЁРТВ*
chat.team=(КОМАНДЕ)
chat.console=Чит