Hint_Annoy1 = Эти подсказки можно выключить в КОНТЕКСТНОМ МЕНЮ
Hint_Annoy2 = Удерживая %+menu_context%, нажмите на ПРОРИСОВКА вверху экрана, а затем на ПОДСКАЗКИ
Hint_OpeningMenu = Нажмите и удерживайте %+menu%, чтобы открыть МЕНЮ СОЗДАНИЯ
Hint_OpeningContext = Нажмите и удерживайте %+menu_context%, чтобы открыть КОНТЕКСТНОЕ МЕНЮ
Hint_ContextClick = Вы также можете использовать ИНСТРУМЕНТЫ, нажимая на экране с открытым КОНТЕКСТНЫМ МЕНЮ
Hint_PhysgunFreeze = Нажмите правую кнопку мыши, чтобы заморозить объект или конечность
Hint_PhysgunUnfreeze = Чтобы разморозить, схватите снова или нажмите на %+reload%, смотря на него. Двойное нажатие %+reload% разморозит всё.
Hint_PhysgunUse = Вы можете вращать объекты ФИЗИЧЕСКОЙ ПУШКОЙ, зажав %+use%
Hint_VehicleView = Используйте %+duck% для переключения между первым и третьим лицом
Hint_ColorRoom = Измените цвет белой комнаты, используя инструмент Цвет!
Hint_EditingSpawnlists = Списки создаваемого можно изменить, переставив иконки внутри списка или перенеся их в другой!
Hint_EditingSpawnlistsSave = Нажмите «Сохранить изменения», чтобы сохранить изменения в списках создаваемого.

hint.unfrozeX = Разморожено объектов: %i
hint.undoneX = Отменён элемент «%s»
hint.hitXlimit = Достигнут лимит элементов «%s»!
hint.cleanedX = Очищены все элементы «%s»
