texturize_pp=НАРКОТА

overlay_pp=Оверлей
overlay_pp.desc=Накладывает материал поверх экрана.
overlay_pp.refract=Сила рефракции:

overlay_pp.binocoverlay=Бинокль
overlay_pp.waterfall=Водопад
overlay_pp.jelly=Желе
overlay_pp.stainedglass=Витраж
overlay_pp.statis=Стазис
overlay_pp.shield=Щит
overlay_pp.froested=Матовое стекло
overlay_pp.tankglass=Топливо
overlay_pp.waves=Волны
overlay_pp.fisheye=Рыбий глаз
overlay_pp.rendertarget=Цель визуализации
overlay_pp.strider_pinch_dudv=Сжатие
overlay_pp.teleport=Телепорт
overlay_pp.teleport2=Телепорт 2
overlay_pp.teleport3=Телепорт 3
overlay_pp.tvnoise=Шум ТВ
overlay_pp.water_warp01=Вода
overlay_pp.jarate=Банкате
overlay_pp.invuln_overlay_red=Убер Красных
overlay_pp.invuln_overlay_blu=Убер Синих
overlay_pp.water_warp=Вода
overlay_pp.bleed_overlay=Кровотёк
overlay_pp.bombinomicon_distortion=Закрутка
overlay_pp.dodge_overlay=Уклонение
overlay_pp.distortion_normal=Искажение

# Shaders

shaders_pp=НАРКОТА

bloom_pp=Свечение
bloom_pp.desc=Может не работать на вашей системе: требуется современная видеокарта.
bloom_pp.enable=Включить
bloom_pp.passes=Проходов:
bloom_pp.darken=Затемнение:
bloom_pp.multiply=Множитель:
bloom_pp.blurx=Горизонт. размытие:
bloom_pp.blury=Вертикал. размытие:
bloom_pp.multiplier=Множитель цвета:
bloom_pp.color=Цвет:

colormod_pp=Изменение цвета
colormod_pp.desc=Изменяет цвета экрана.
colormod_pp.enable=Включить
colormod_pp.brightness=Яркость:
colormod_pp.contrast=Контрастность:
colormod_pp.color=Множитель цвета:
colormod_pp.color_add=Добавочный цвет:
colormod_pp.color_multiply=Цвет множителя:
colormod_pp.invert=Инверсия цвета:

sobel_pp=Оператор Собеля
sobel_pp.desc=Выделяет все края.
sobel_pp.enable=Включить
sobel_pp.threshold=Порог:

toytown_pp=Игрушечный город
toytown_pp.desc=Также известен как эффект диорамы. Если используется правильно, может сделать сцену похожей на миниатюру.
toytown_pp.enable=Включить
toytown_pp.passes=Проходов:
toytown_pp.height=Высота:

sunbeams_pp=Солнечный
sunbeams_pp.desc=Создаёт объёмные эффекты солнечных лучей, исходящих от солнца.
sunbeams_pp.enable=Включить
sunbeams_pp.multiply=Множитель:
sunbeams_pp.darken=Затемнение:
sunbeams_pp.size=Размер солнца:

sharpen_pp=Резкость
sharpen_pp.desc=Изменяет резкость всего на экране.
sharpen_pp.enable=Включить
sharpen_pp.distance=Расстояние:
sharpen_pp.contrast=Контрастность:

# Effects

effects_pp=Наркота

stereoscopy_pp=Стереоскопия
stereoscopy_pp.desc=Garry's Mod в поддельном 3D!
stereoscopy_pp.enable=Включить
stereoscopy_pp.size=Размер:

superdof_pp=Суперглубина резкости
superdof_pp.title=Суперглубина резкости
superdof_pp.settings=Настройки
superdof_pp.size=Величина размытия:
superdof_pp.distance=Расстояние фокусировки:
superdof_pp.distance.tooltip=Расстояние фокусировки. Также вы можете просто нажать мышью на экране, чтобы сфокусироваться на нужной точке.
superdof_pp.adv=Расширенные настройки
superdof_pp.passes=Проходов:
superdof_pp.shape=Форма:
superdof_pp.radials=Радиалов:
superdof_pp.render=Прорисовка
superdof_pp.screenshot=Сделать скриншот
superdof_pp.5hint=Скрыть это окно на 5 секунд

frame_blend_pp=Смешение кадров
frame_blend_pp.desc=Это своего рода размытие движения, использующееся программами для редактирования видео.
frame_blend_pp.desc2=Предупреждение: снижает частоту кадров.
frame_blend_pp.enable=Включить
frame_blend_pp.frames=Кадров:
frame_blend_pp.shutter=Затвор:

motion_blur_pp=Размытие
motion_blur_pp.desc=Создаёт грубый эффект размытия движения путём накладывания предыдущего кадра на последующий.
motion_blur_pp.enable=Включить
motion_blur_pp.add_alpha=Прозрачность:
motion_blur_pp.draw_alpha=Прозрачность прорисовки:
motion_blur_pp.delay=Задержка захвата:

dof_pp=Глубина резкости
dof_pp.desc=Делает фон вне фокуса.
dof_pp.enable=Включить
dof_pp.spacing=Межузловое расстояние:
dof_pp.start_distance=Начальное расстояние:

texturize_pp.plain=Простая
texturize_pp.pattern1=Сетка
texturize_pp.rainbow=ЛСД
texturize_pp.lines=Линии
texturize_pp.pinko=Розово
texturize_pp.squaredo=Квадрато
