spawnmenu.content_tab=Списки создаваемого

spawnmenu.category.npcs=НИПы
spawnmenu.category.addons=Дополнения
spawnmenu.category.weapons=Оружие
spawnmenu.category.postprocess=Постобработка
spawnmenu.category.your_spawnlists=Ваши списки создаваемого
spawnmenu.category.addon_spawnlists=Списки создаваемого дополнений
spawnmenu.category.games=Игры
spawnmenu.category.browse=Обзор
spawnmenu.category.entities=Энтити
spawnmenu.category.vehicles=Транспорт
spawnmenu.category.creations=Творения
spawnmenu.category.dupes=Дубликаты
spawnmenu.category.saves=Сохранения

spawnmenu.tools_tab=Инструменты
spawnmenu.tools.constraints=Крепления
spawnmenu.tools.construction=Строительство
spawnmenu.tools.posing=Позинг
spawnmenu.tools.render=Прорисовка
spawnmenu.tools.disabled=Этот инструмент выключен сервером!

spawnmenu.menu.copy=Скопировать в буфер обмена
spawnmenu.menu.delete=Удалить
spawnmenu.menu.deletex=Удалить %i шт.
spawnmenu.menu.edit=Изменить
spawnmenu.menu.new=Новый
spawnmenu.menu.copy_dnd=Скопировать
spawnmenu.menu.move=Переместить
spawnmenu.menu.new_category=Новая категория
spawnmenu.menu.add_subcategory=Добавить подкатегорию
spawnmenu.menu.edit_icon=Изменить иконку
spawnmenu.menu.resize=Размер
spawnmenu.menu.resizex=Изменить размер %i шт.
spawnmenu.menu.rerender=Перерисовать
spawnmenu.menu.rerenderx=Перерисовать %i шт.
spawnmenu.menu.rerender_this=Эту иконку
spawnmenu.menu.rerender_all=Все иконки
spawnmenu.menu.spawn_with_toolgun=Создать с помощью инструмента-пушки
spawnmenu.menu.use_as_npc_gun=Использовать как замену оружия НИПам
spawnmenu.menu.spawn_with_weapon=Создать с оружием

spawnmenu.savechanges=Сохранить изменения
spawnmenu.revert=Сброс
spawnmenu.revert_tooptip=Отмена всех изменений в списках создаваемого
spawnmenu.search=Поиск...
spawnmenu.filter=Фильтр...
spawnmenu.quick_search=Быстрый поиск...
spawnmenu.quick_search_tool=Быстрый поиск:
spawnmenu.quick_filter=Быстрый фильтр...
spawnmenu.quick_filter_tool=Быстрый фильтр:
spawnmenu.enter_search=Нажмите Enter для поиска
spawnmenu.press_search=Нажмите, чтобы начать поиск
spawnmenu.header_tooltip=Перетащите вправо, чтобы добавить редактируемый заголовок раздела в список создаваемого
spawnmenu.listname_tooltip=Название выбранного списка создаваемого
spawnmenu.newlabel=Новый текстовый заголовок
spawnmenu.spawnlistnocontent=Этому списку создаваемого требуется %s, который не смонтирован!
spawnmenu.mountablegame=монтируемая игра
spawnmenu.createautospawnlist=Создать список создаваемого из этой папки
spawnmenu.openaddononworkshop=Открыть в мастерской Steam
spawnmenu.mmb_weapons=Вы можете использовать среднюю кнопку мыши, чтобы создать оружие под прицелом.

spawnmenu.utilities_tab=Утилиты
spawnmenu.utilities.user=Пользователь
spawnmenu.utilities.admin=Администратор
spawnmenu.utilities.settings=Настройки
spawnmenu.utilities.cleanup=Очистка
spawnmenu.utilities.cleanup.help=Очистка группы элементов.
spawnmenu.utilities.cleanup.all=Очистить всё
spawnmenu.utilities.undo=Отмена
spawnmenu.utilities.undo.help=Отмена предыдущих действий.
spawnmenu.utilities.physgunsettings=Настройки физпушки
spawnmenu.utilities.sandbox_settings=Настройки песочницы
spawnmenu.utilities.server_settings=Настройки сервера

utilities.serversettings=Настройки сервера. Эти настройки могут быть изменены только создателем сервера через главное меню.
utilities.password=Пароль сервера:
utilities.gravity=Гравитация:
utilities.timescale=Скорость физики:
utilities.iterations=Итерация физики:
utilities.kickerrornum=Выгонять за клиентские ошибки
utilities.allowcslua=Разрешить клиентские скрипты
utilities.sticktoground=Придерживаться земли
utilities.sticktoground.help=Если включено, игроки будут придерживаться земли при ударе о склон на высоких скоростях. Если выключено, игроки будут отскакивать/скользить вперёд.
utilities.epickupallowed=Подъём предметов клавишей взаимодействия
utilities.falldamage=Реалистичный урон от падения
utilities.maxammo=Макс. боезапас:
utilities.maxammo.help=Устанавливает максимальный боезапас для всех видов оружия каждого игрока. При значениях 0 и ниже используется максимум, установленный в настройках боеприпасов.
utilities.gmod_suit=Включить функциональность костюма HEV
utilities.friction=Наземное трение:
utilities.deployspeed=Скорость вытаскивания оружия:
utilities.noclipspeed=Скорость полёта:
utilities.sv_timeout=Время ожидания клиента:
utilities.hostname=Название сервера:
utilities.max_ragdolls=Максимум рэгдоллов:
utilities.max_ragdolls.help=Ограничивает количество трупов НИПов и осколков от объектов.

utilities.sandboxsettings=Настройки песочницы. Эти настройки могут быть изменены только создателем сервера через главное меню.
utilities.sandboxsettings_cl=Клиентские настройки песочницы. Они влияют только на вашу игру.
utilities.max_results=Макс. результатов поиска
utilities.max_results.help=Максимальное количество отображаемых результатов поиска в меню создания. Большие значения могут вызвать проблемы с производительностью.
utilities.mp_only=Следующие настройки применимы только в сетевой игре.
utilities.spawnmenu_toggle=Залипание контекстного меню и создаваемого
utilities.spawnmenu_toggle.help=Меню создаваемого и контекстное меню не закроются, если нажать на клавишу быстро. Нажмите её вновь, чтобы закрыть.

utilities.physgunsettings=Клиентские настройки физической пушки. Эти настройки сохраняются в течение множества сеансов.
utilities.gm_snapgrid=Размер сетки положения:
utilities.gm_snapangles=Угол привязки:
utilities.physgun_rotation_sensitivity=Чувствительность вращения:
utilities.physgun_wheelspeed=Скорость колеса:
utilities.physgun_drawbeams=Отображать лучи физпушки
utilities.physgun_halo=Отображать свечение при подъёме физпушкой

utilities.physgunsvsettings=Серверные настройки физической пушки. Эти настройки могут быть изменены только создателем сервера через главное меню.
utilities.physgun_maxrange=Макс. дальность луча:
utilities.physgun_limited=Ограниченная физпушка
utilities.physgun_limited.help=Если включено, физическая пушка не сможет поднимать определённые объекты карты.
utilities.physgun_tpdist=Расстояние телепорта:
utilities.physgun_maxspeed=Макс. скорость объекта:
utilities.physgun_maxangular=Макс. скорость поворота:
utilities.physgun_timetoarrive=Время прибытия:
utilities.physgun_timetoarriveragdoll=Время прибытия (рэгдолл):
utilities.physgun_timetoarriveragdoll.help=Время в секундах, необходимое для прибытия рэгдолла туда, куда указывает физическая пушка.

spawnmenu.searchindex=Добавление установленных моделей в поиск меню создания...
spawnmenu.failedtofindmodels=Не удалось найти модели для этого дополнения.
Обычно это происходит, когда несколько дополнений имеют одинаковые пути к моделям.

smwidget.icon_editor=Редактор иконок
smwidget.playermodel=Модель игрока
smwidget.playermodel_title=Выбор модели игрока
smwidget.model=Модель
smwidget.colors=Цвета
smwidget.color_plr=Цвет игрока:
smwidget.color_wep=Цвет оружия:
smwidget.bodygroups=Группы тела
smwidget.animations=Анимации
smwidget.settings=Настройки

# DBinder
dbinder.none=НЕТ
dbinder.press_a_key=НАЖМИТЕ КЛАВИШУ
dbinder.help=Левая кнопка мыши: сменить
Правая кнопка мыши: очистить
Средняя кнопка мыши: стандартная клавиша (если возможно)

KP_INS=Numpad 0
KP_END=Numpad 1
KP_DOWNARROW=Numpad 2
KP_PGDN=Numpad 3
KP_LEFTARROW=Numpad 4
KP_5=Numpad 5
KP_RIGHTARROW=Numpad 6
KP_HOME=Numpad 7
KP_UPARROW=Numpad 8
KP_PGUP=Numpad 9
KP_DEL=Numpad .
KP_ENTER=Numpad Enter
KP_PLUS=Numpad +
KP_MINUS=Numpad -
KP_SLASH=Numpad /
KP_MULTIPLY=Numpad *

# Vehicles
spawnmenu.vehicle.jeep=Джип
spawnmenu.vehicle.airboat=Воздушный катер
spawnmenu.vehicle.jalopy=Драндулет
spawnmenu.vehicle.prisoner_pod=Капсула заключённых

spawnmenu.chair.wooden=Деревянный стул
spawnmenu.chair.office=Офисное кресло
spawnmenu.chair.office_big=Большое офисное кресло
spawnmenu.chair.plastic=Пластиковый стул

spawnmenu.seat.jeep=Сиденье джипа
spawnmenu.seat.jalopy=Сиденье драндулета
spawnmenu.seat.airboat=Сиденье катера
spawnmenu.seat.simple_sit=Сиденье (обычное)
spawnmenu.seat.simple_jeep=Сиденье (джип)
spawnmenu.seat.simple_airboat=Сиденье (катер)

# Spawnmenu entity categories
spawnmenu.category.fun_games=Веселье + игры
spawnmenu.category.editors=Редакторы
spawnmenu.category.humans_resistance=Люди + Сопротивление
spawnmenu.category.zombies_aliens=Зомби + вражеские пришельцы
spawnmenu.category.animals=Животные
spawnmenu.category.combine=Альянс
spawnmenu.category.chairs=Стулья
spawnmenu.category.other=Прочее

# Weapon selector & spawnmenu entity icon tooltips
entityinfo.author=Автор:
entityinfo.contact=Контакты:
entityinfo.purpose=Назначение:
entityinfo.instructions=Инструкции:

# Undo
undo.generic.npc=НИП
undo.generic.entity=Энтити
undo.generic.weapon=Оружие
undo.generic.vehicle=Транспорт
undo.duplication=Дубликат
